FROM alpine:edge AS builder
RUN apk add linux-headers build-base make bash gcc g++ git cmake python3
RUN apk add ninja zip unzip curl musl-dev
RUN apk add elfutils-dev libelf-static zlib-static bzip2-static

WORKDIR /src
COPY . .
RUN cp docker/vcpkg-alpine.json vcpkg.json
ENV VCPKG_FORCE_SYSTEM_BINARIES=1
RUN cmake --preset=release-vcpkg-static
RUN cmake --build --preset=release-vcpkg-static
RUN cp build/release-vcpkg-static/bin/poorprof /poorprof
RUN ldd /poorprof || true
