LIST(PREPEND CMAKE_FIND_LIBRARY_SUFFIXES .a)

find_package(fmt REQUIRED)
list(APPEND POORPROF_PRIVATE_LIBRARIES fmt::fmt)

find_package(ElfUtils REQUIRED)
list(APPEND POORPROF_PRIVATE_LIBRARIES ${LIBDWARF_LIBRARIES} ${LIBDW_LIBRARIES} ${LIBELF_LIBRARIES})

find_package(absl REQUIRED)
list(APPEND POORPROF_PRIVATE_LIBRARIES absl::flat_hash_map)

find_package(spdlog REQUIRED)
list(APPEND POORPROF_PRIVATE_LIBRARIES spdlog::spdlog)

set(Boost_USE_STATIC_LIBS ON)
find_package(Boost REQUIRED COMPONENTS iostreams)
list(APPEND POORPROF_PRIVATE_LIBRARIES Boost::iostreams)
